---
- hosts: all
  become: yes
  
  tasks:
    - name: start
      shell: docker run -d --net="host" --pid="host" -v "/:/host:ro,rslave" --restart=always quay.io/prometheus/node-exporter --path.rootfs /host 